name: Deploy Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (staging or prod)"
        required: true
        default: staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout student repo
        uses: actions/checkout@v4

      - name: Set REPO_NAME and DEPLOY_PATH
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          DEPLOY_ENV="${{ github.event.inputs.environment }}"
          DEPLOY_PATH="${REPO_NAME}.${DEPLOY_ENV}"

          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "DEPLOY_ENV=$DEPLOY_ENV" >> $GITHUB_ENV
          echo "DEPLOY_PATH=$DEPLOY_PATH" >> $GITHUB_ENV

      - name: Set HOST_IP and write vault
        run: |
          if [ "${{ github.event.inputs.environment }}" = "prod" ]; then
            HOST_IP=${{ secrets.PROD_HOST }}
            VAULT="${{ secrets.VAULT_PROD }}"
          else
            HOST_IP=${{ secrets.STAGING_HOST }}
            VAULT="${{ secrets.VAULT_STAGING }}"
          fi

          echo "HOST_IP=$HOST_IP" >> $GITHUB_ENV
          mkdir -p ansible/group_vars/${{ github.event.inputs.environment }}
          echo "$VAULT" > ansible/group_vars/${{ github.event.inputs.environment }}/vault.yml

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      - name: Clone core infra
        run: git clone https://github.com/codeworks-templates/postgres-core.git core-template
      
      - name: Inject student templates + vault into core
        run: |
          mkdir -p core-template/ansible/templates
          mkdir -p core-template/ansible/group_vars
          cp -r ansible/templates/* core-template/ansible/templates/
          cp -r ansible/group_vars/* core-template/ansible/group_vars/

      - name: Create inventory.ini dynamically
        run: |
          echo "[${{ github.event.inputs.environment }}]" > inventory.ini
          echo "target ansible_host=$HOST_IP ansible_user=${{ secrets.SSH_USER }}" >> inventory.ini

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Disable SSH host key checking
        run: echo "StrictHostKeyChecking=no" >> ~/.ssh/config

      - name: Upload stack to remote server
        run: |
          scp -r core-template/* ${{ secrets.SSH_USER }}@$HOST_IP:/home/${{ secrets.SSH_USER }}/$DEPLOY_PATH/


      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini core-template/ansible/playbook.yml \
            --extra-vars "deploy_env=$DEPLOY_ENV repo_name=$DEPLOY_PATH"

